---

- name: add GO CD apt repository
  sudo: yes
  apt_repository:
    repo: deb http://dl.bintray.com/gocd/gocd-deb/ /
    state: present

- name: install go-server
  sudo: yes
  apt:
    name: "go-agent={{ gocd_agent.version }}"
    state: present
    force: yes

- name: enable go-agent
  sudo: yes
  service:
    name: go-agent
    enabled: yes
    state: started
